services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6001:6001"

  frontend:
    image: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"