apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: myapp
        image: mpaserrano/backend-17-10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6001
        env:
        - name: SECRET
          value: "MySecret1!"
        - name: MONGODB_URI
          value: "mongodb+srv://dionamite:Dionamite1!@portalformadores.mob88xm.mongodb.net/flor?retryWrites=true&w=majority&appName=PortalFormadores"
        - name: CLOUD_NAME
          value: "drsjloigq"
        - name: CLOUD_API_KEY
          value: "926793658896175"
        - name: CLOUD_API_SECRET
          value: "5QhoDhOiODpETRSYUrRYDzu5tv0"