apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_DB
          value: restaurant-db
        ports:
        - containerPort: 5432
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - admin
            - -d
            - restaurant-db
            - -c
            - "SELECT 1;"
          initialDelaySeconds: 10
          periodSeconds: 1
        volumeMounts:
        - mountPath: /var/lib/postgresql/data  # Path inside the container
          name: efs-storage
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-pvc
